"""research sessions

Revision ID: 5f21c1cb34d0
Revises: 6d095cdffa5f
Create Date: 2026-08-29 06:40:58.444304
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '5f21c1cb34d0'
down_revision: str | None = '6d095cdffa5f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'research_sessions',
        sa.Column('research_session_id', sa.String(length=36), nullable=False),
        sa.Column('question', sa.Text(), nullable=False),
        sa.Column('context', sa.Text(), nullable=False),
        sa.Column('mode', sa.String(length=16), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('max_angles', sa.Integer(), nullable=False),
        sa.Column('angles_planned', sa.JSON(), nullable=False),
        sa.Column('runs_completed', sa.Integer(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('report_id', sa.String(length=36), nullable=True),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('finished_at', sa.DateTime(), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint('research_session_id')
    )
    op.create_index(
        op.f('ix_research_sessions_created_at'),
        'research_sessions',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_research_sessions_status'),
        'research_sessions',
        ['status'],
        unique=False,
    )
    op.add_column('dot_runs', sa.Column('session_id', sa.String(length=36), nullable=True))
    op.create_index(
        op.f('ix_dot_runs_session_id'), 'dot_runs', ['session_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dot_runs_session_id'), table_name='dot_runs')
    op.drop_column('dot_runs', 'session_id')
    op.drop_index(op.f('ix_research_sessions_status'), table_name='research_sessions')
    op.drop_index(op.f('ix_research_sessions_created_at'), table_name='research_sessions')
    op.drop_table('research_sessions')
    # ### end Alembic commands ###
