"""initial schema

Revision ID: 6d095cdffa5f
Revises: None
Create Date: 2026-08-29 06:30:38.683130
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '6d095cdffa5f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changes',
    sa.Column('change_id', sa.String(length=36), nullable=False),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('object_key', sa.String(length=256), nullable=False),
    sa.Column('attribute', sa.String(length=128), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('change_id')
    )
    op.create_index(op.f('ix_changes_change_type'), 'changes', ['change_type'], unique=False)
    op.create_index(op.f('ix_changes_detected_at'), 'changes', ['detected_at'], unique=False)
    op.create_index(op.f('ix_changes_object_key'), 'changes', ['object_key'], unique=False)
    op.create_index(op.f('ix_changes_severity'), 'changes', ['severity'], unique=False)
    op.create_table('dot_batches',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('dot_run_id', sa.String(length=36), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('queries', sa.JSON(), nullable=False),
    sa.Column('hits_found', sa.Integer(), nullable=False),
    sa.Column('content_ids', sa.JSON(), nullable=False),
    sa.Column('kept_ids', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_dot_batches_created_at'), 'dot_batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_dot_batches_dot_run_id'), 'dot_batches', ['dot_run_id'], unique=False)
    op.create_table('dot_runs',
    sa.Column('dot_run_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('iterations_target', sa.Integer(), nullable=False),
    sa.Column('iterations_done', sa.Integer(), nullable=False),
    sa.Column('providers', sa.JSON(), nullable=False),
    sa.Column('queries_per_round', sa.Integer(), nullable=False),
    sa.Column('max_items_per_round', sa.Integer(), nullable=False),
    sa.Column('dots_kept', sa.Integer(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reasoning_log', sa.JSON(), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('dot_run_id')
    )
    op.create_index(op.f('ix_dot_runs_created_at'), 'dot_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_dot_runs_status'), 'dot_runs', ['status'], unique=False)
    op.create_table('dot_watches',
    sa.Column('dot_watch_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=512), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('providers', sa.JSON(), nullable=False),
    sa.Column('queries_per_round', sa.Integer(), nullable=False),
    sa.Column('max_items_per_round', sa.Integer(), nullable=False),
    sa.Column('interval_hours', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_id', sa.String(length=36), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_dot_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('dot_watch_id')
    )
    op.create_index(op.f('ix_dot_watches_enabled'), 'dot_watches', ['enabled'], unique=False)
    op.create_index(
        op.f('ix_dot_watches_next_run_at'), 'dot_watches', ['next_run_at'], unique=False
    )
    op.create_table('entities',
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('name_key', sa.String(length=320), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_index(op.f('ix_entities_kind'), 'entities', ['kind'], unique=False)
    op.create_index(op.f('ix_entities_last_seen'), 'entities', ['last_seen'], unique=False)
    op.create_index(op.f('ix_entities_name_key'), 'entities', ['name_key'], unique=True)
    op.create_table('entity_relations',
    sa.Column('relation_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('relation', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_index(
        op.f('ix_entity_relations_last_seen'), 'entity_relations', ['last_seen'], unique=False
    )
    op.create_index(
        op.f('ix_entity_relations_object_id'), 'entity_relations', ['object_id'], unique=False
    )
    op.create_index(
        op.f('ix_entity_relations_subject_id'), 'entity_relations', ['subject_id'], unique=False
    )
    op.create_table('evidence',
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_index(op.f('ix_evidence_content_hash'), 'evidence', ['content_hash'], unique=False)
    op.create_index(op.f('ix_evidence_fetched_at'), 'evidence', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_evidence_source'), 'evidence', ['source'], unique=False)
    op.create_index(op.f('ix_evidence_source_type'), 'evidence', ['source_type'], unique=False)
    op.create_index(op.f('ix_evidence_url'), 'evidence', ['url'], unique=False)
    op.create_table('hypotheses',
    sa.Column('hypothesis_id', sa.String(length=36), nullable=False),
    sa.Column('statement', sa.String(length=1024), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('entity_ids', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('oracle_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('hypothesis_id')
    )
    op.create_index(op.f('ix_hypotheses_created_at'), 'hypotheses', ['created_at'], unique=False)
    op.create_index(op.f('ix_hypotheses_status'), 'hypotheses', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('hypothesis_ids', sa.JSON(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('entity_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_hypotheses_status'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_created_at'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_evidence_url'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_source_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_source'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_fetched_at'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_content_hash'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_entity_relations_subject_id'), table_name='entity_relations')
    op.drop_index(op.f('ix_entity_relations_object_id'), table_name='entity_relations')
    op.drop_index(op.f('ix_entity_relations_last_seen'), table_name='entity_relations')
    op.drop_table('entity_relations')
    op.drop_index(op.f('ix_entities_name_key'), table_name='entities')
    op.drop_index(op.f('ix_entities_last_seen'), table_name='entities')
    op.drop_index(op.f('ix_entities_kind'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_dot_watches_next_run_at'), table_name='dot_watches')
    op.drop_index(op.f('ix_dot_watches_enabled'), table_name='dot_watches')
    op.drop_table('dot_watches')
    op.drop_index(op.f('ix_dot_runs_status'), table_name='dot_runs')
    op.drop_index(op.f('ix_dot_runs_created_at'), table_name='dot_runs')
    op.drop_table('dot_runs')
    op.drop_index(op.f('ix_dot_batches_dot_run_id'), table_name='dot_batches')
    op.drop_index(op.f('ix_dot_batches_created_at'), table_name='dot_batches')
    op.drop_table('dot_batches')
    op.drop_index(op.f('ix_changes_severity'), table_name='changes')
    op.drop_index(op.f('ix_changes_object_key'), table_name='changes')
    op.drop_index(op.f('ix_changes_detected_at'), table_name='changes')
    op.drop_index(op.f('ix_changes_change_type'), table_name='changes')
    op.drop_table('changes')
    # ### end Alembic commands ###
